import type { Metadata } from 'next';
import { Noto_Sans_Khmer } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
	title: 'Home | Next.js',
	description: 'Generated by create next app',
};

const inter = Noto_Sans_Khmer({
	subsets: ['khmer'],
	weight: '400',
});

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	return (
		<html lang={locale} className={inter.className}>
			<body>{children}</body>
		</html>
	);
}
